### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by sten97** [CourseNotesBTH/MA1454#1]
- [ ] Typo on row 124 "Simsons regel" should be "Simpsons regel".-
- [ ] Missing parentheses on row 157 in Simpsons formel 
"S(h) = \frac{h}{3}\left\{f(x_0) + 4f(x_1) + 2f(x_2) + \dots + 2f(x_{n-2}) + 4f(x_{n-1} + f(x_n)\right\}"
should be 
"S(h) = \frac{h}{3}\left\{f(x_0) + 4f(x_1) + 2f(x_2) + \dots + 2f(x_{n-2}) + 4f(x_{n-1}) + f(x_n)\right\}"

**Comment by AlexGustafsson** [comment]
Fixed in https://github.com/CourseNotesBTH/MA1454/commit/bcd6fe74dad2edf685e70dc9b37237dad1391b4c. Closing.
